# Generated by Django 4.2 on 2024-03-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
    ]
